import type { Member } from "./types";

/**
 * Profils synthétiques. Aucune donnée personnelle réelle.
 * Coordonnées = quartiers réels de Marseille, pour la carte 3D.
 */
export const MEMBERS: Member[] = [
  {
    id: "sonia", firstName: "Sonia", lastName: "Berthier", job: "Directrice artistique",
    company: "Studio Mistral", age: 38, neighborhood: "Le Panier", coords: [5.3689, 43.2989],
    zodiac: "Cancer",
    linkedin: "linkedin.com/in/sonia-berthier",
    joinedAt: "2023-02-14",
    skills: ["identité visuelle", "print", "direction artistique", "packaging"],
    offers: ["refonte de marque", "charte graphique"],
    needs: ["clients grands comptes", "développeuse web"],
    hobbies: ["céramique", "randonnée", "cinéma"],
    bio: "15 ans de branding, je fais parler les marques qui ont quelque chose à dire.",
    knows: ["leila", "fatima", "claire"], mentor: true,
  },
  {
    id: "leila", firstName: "Leïla", lastName: "Haddad", job: "Avocate en droit des affaires",
    company: "Cabinet Haddad", age: 44, neighborhood: "Castellane", coords: [5.3832, 43.2861],
    zodiac: "Sagittaire",
    linkedin: "linkedin.com/in/leila-haddad",
    joinedAt: "2022-09-06",
    skills: ["droit des sociétés", "contrats", "levée de fonds", "propriété intellectuelle"],
    offers: ["audit juridique", "négociation de contrats"],
    needs: ["visibilité LinkedIn", "assistante juridique"],
    hobbies: ["natation", "opéra", "vin nature"],
    bio: "J'accompagne les fondatrices sur tout ce qui se signe.",
    knows: ["sonia", "claire", "nadia"], mentor: true,
  },
  {
    id: "fatima", firstName: "Fatima", lastName: "Ould-Ali", job: "Développeuse web freelance",
    company: "Indépendante", age: 29, neighborhood: "La Plaine", coords: [5.3861, 43.2941],
    zodiac: "Taureau",
    linkedin: "linkedin.com/in/fatima-ould-ali",
    joinedAt: "2024-01-20",
    skills: ["React", "Next.js", "Node", "accessibilité"],
    offers: ["site vitrine", "application métier", "audit technique"],
    needs: ["apporteuses d'affaires", "comptable"],
    hobbies: ["escalade", "jeux de société", "techno"],
    bio: "Je code des produits qui tiennent la charge et qui restent lisibles.",
    knows: ["sonia", "ines"],
  },
  {
    id: "claire", firstName: "Claire", lastName: "Vasseur", job: "Consultante RSE",
    company: "Vasseur & Co", age: 41, neighborhood: "Vieux-Port", coords: [5.3740, 43.2951],
    zodiac: "Balance",
    linkedin: "linkedin.com/in/claire-vasseur",
    joinedAt: "2022-11-03",
    skills: ["bilan carbone", "reporting CSRD", "stratégie RSE", "formation"],
    offers: ["diagnostic RSE", "accompagnement label"],
    needs: ["graphiste pour rapports", "juriste environnement"],
    hobbies: ["voile", "jardinage", "podcasts"],
    bio: "La RSE utile : des chiffres, des preuves, pas du vernis.",
    knows: ["sonia", "leila", "amelie"], mentor: true,
  },
  {
    id: "nadia", firstName: "Nadia", lastName: "Benali", job: "Fondatrice traiteur",
    company: "Table Nomade", age: 35, neighborhood: "Noailles", coords: [5.3792, 43.2952],
    zodiac: "Poissons",
    linkedin: "linkedin.com/in/nadia-benali",
    joinedAt: "2023-06-11",
    skills: ["traiteur événementiel", "cuisine méditerranéenne", "logistique"],
    offers: ["cocktails d'entreprise", "ateliers cuisine"],
    needs: ["carnet d'adresses entreprises", "photographe culinaire"],
    hobbies: ["marchés", "course à pied", "voyages"],
    bio: "Je nourris vos événements, du cocktail de 20 au séminaire de 300.",
    knows: ["leila", "ines"],
  },
  {
    id: "ines", firstName: "Inès", lastName: "Moretti", job: "Photographe",
    company: "Studio Inès M.", age: 32, neighborhood: "Endoume", coords: [5.3549, 43.2856],
    zodiac: "Lion",
    linkedin: "linkedin.com/in/ines-moretti",
    joinedAt: "2023-09-28",
    skills: ["portrait corporate", "photo culinaire", "retouche", "vidéo courte"],
    offers: ["shooting portraits", "reportage d'événement"],
    needs: ["clients récurrents", "assistante plateau"],
    hobbies: ["plongée", "expositions", "vinyles"],
    bio: "Des portraits qui ne sentent pas la photo d'entreprise.",
    knows: ["fatima", "nadia"],
  },
  {
    id: "amelie", firstName: "Amélie", lastName: "Rossi", job: "Formatrice en communication",
    company: "Prendre la parole", age: 47, neighborhood: "Longchamp", coords: [5.3936, 43.3036],
    zodiac: "Capricorne",
    linkedin: "linkedin.com/in/amelie-rossi",
    joinedAt: "2022-04-15",
    skills: ["prise de parole", "média training", "pitch", "storytelling"],
    offers: ["coaching pitch", "formation orale"],
    needs: ["plateforme e-learning", "développeuse"],
    hobbies: ["théâtre", "yoga", "lecture"],
    bio: "Votre idée est bonne. Encore faut-il qu'on l'entende.",
    knows: ["claire", "beatrice"], mentor: true,
  },
  {
    id: "beatrice", firstName: "Béatrice", lastName: "Lorenzi", job: "Experte-comptable",
    company: "Cabinet Lorenzi", age: 52, neighborhood: "Prado", coords: [5.3906, 43.2724],
    zodiac: "Gémeaux",
    linkedin: "linkedin.com/in/beatrice-lorenzi",
    joinedAt: "2021-10-02",
    skills: ["comptabilité", "prévisionnel", "fiscalité", "subventions"],
    offers: ["bilan", "business plan chiffré"],
    needs: ["outils d'automatisation", "community manager"],
    hobbies: ["golf", "cuisine", "mots croisés"],
    bio: "Je transforme vos chiffres en décisions.",
    knows: ["amelie", "sophie"], mentor: true,
  },
  {
    id: "sophie", firstName: "Sophie", lastName: "Da Costa", job: "Architecte d'intérieur",
    company: "Atelier SDC", age: 39, neighborhood: "Roucas Blanc", coords: [5.3627, 43.2760],
    zodiac: "Scorpion",
    linkedin: "linkedin.com/in/sophie-da-costa",
    joinedAt: "2023-03-22",
    skills: ["agencement", "3D", "suivi de chantier", "mobilier sur mesure"],
    offers: ["aménagement de bureaux", "home staging"],
    needs: ["artisans fiables", "visibilité presse"],
    hobbies: ["brocantes", "vélo", "design"],
    bio: "Des espaces où l'on a envie de rester.",
    knows: ["beatrice", "karine"],
  },
  {
    id: "karine", firstName: "Karine", lastName: "Fabre", job: "Coach professionnelle",
    company: "Cap sur soi", age: 49, neighborhood: "Vauban", coords: [5.3703, 43.2861],
    zodiac: "Bélier",
    linkedin: "linkedin.com/in/karine-fabre",
    joinedAt: "2022-01-18",
    skills: ["coaching de dirigeantes", "gestion du stress", "transition pro"],
    offers: ["accompagnement individuel", "ateliers collectifs"],
    needs: ["prescripteurs", "site refait"],
    hobbies: ["méditation", "marche", "aquarelle"],
    bio: "On travaille sur ce qui bloque, pas sur ce qui se voit.",
    knows: ["sophie", "amelie"], mentor: true,
  },
  {
    id: "yasmine", firstName: "Yasmine", lastName: "Kaddour", job: "Consultante IA",
    company: "Kaddour Data", age: 31, neighborhood: "Joliette", coords: [5.3644, 43.3062],
    zodiac: "Vierge",
    linkedin: "linkedin.com/in/yasmine-kaddour",
    joinedAt: "2024-05-07",
    skills: ["automatisation", "LLM", "data", "no-code"],
    offers: ["audit d'automatisation", "agents métiers"],
    needs: ["clients PME", "juriste RGPD"],
    hobbies: ["escalade", "science-fiction", "running"],
    bio: "J'installe de l'IA qui sert vraiment, ou je le dis franchement.",
    knows: ["fatima"], isNewcomer: true,
  },
  {
    id: "helene", firstName: "Hélène", lastName: "Marchand", job: "Attachée de presse",
    company: "Marchand RP", age: 43, neighborhood: "Notre-Dame-du-Mont", coords: [5.3843, 43.2913],
    zodiac: "Verseau",
    linkedin: "linkedin.com/in/helene-marchand",
    joinedAt: "2023-01-09",
    skills: ["relations presse", "réseaux sociaux", "communiqués"],
    offers: ["campagne presse", "media list"],
    needs: ["photographe", "clientes tech"],
    hobbies: ["festivals", "surf", "écriture"],
    bio: "Je fais parler de vous, dans les bons médias.",
    knows: ["ines", "claire"],
  },
  {
    id: "maud", firstName: "Maud", lastName: "Peretti", job: "Fondatrice cosmétique",
    company: "Calanque Beauty", age: 36, neighborhood: "Bonneveine", coords: [5.3775, 43.2513],
    zodiac: "Cancer",
    linkedin: "linkedin.com/in/maud-peretti",
    joinedAt: "2023-11-14",
    skills: ["formulation", "sourcing", "retail", "e-commerce"],
    offers: ["private label", "conseil produit"],
    needs: ["distribution", "packaging écoconçu"],
    hobbies: ["paddle", "botanique", "cuisine"],
    bio: "Des cosmétiques sourcés en Méditerranée, sans greenwashing.",
    knows: ["maya"],
  },
  {
    id: "maya", firstName: "Maya", lastName: "Sissoko", job: "Cheffe de projet événementiel",
    company: "Sissoko Events", age: 33, neighborhood: "Cours Julien", coords: [5.3830, 43.2925],
    zodiac: "Sagittaire",
    linkedin: "linkedin.com/in/maya-sissoko",
    joinedAt: "2024-02-26",
    skills: ["production événementielle", "régie", "budget", "scénographie"],
    offers: ["organisation de séminaires", "lancements produit"],
    needs: ["traiteur", "lieux atypiques"],
    hobbies: ["danse", "concerts", "cuisine"],
    bio: "Je produis des événements qui tournent sans accroc.",
    knows: ["maud", "nadia"],
  },
  {
    id: "camille", firstName: "Camille", lastName: "Aubert", job: "Traductrice technique",
    company: "Aubert Traductions", age: 45, neighborhood: "Saint-Victor", coords: [5.3641, 43.2907],
    zodiac: "Taureau",
    linkedin: "linkedin.com/in/camille-aubert",
    joinedAt: "2022-07-19",
    skills: ["traduction EN/FR", "localisation", "rédaction technique"],
    offers: ["localisation de site", "relecture"],
    needs: ["agences partenaires", "comptable"],
    hobbies: ["randonnée", "langues", "chorale"],
    bio: "Vos textes en anglais, sans accent français.",
    knows: ["helene", "therese"],
  },
  {
    id: "rachida", firstName: "Rachida", lastName: "Ziani", job: "Consultante financière",
    company: "RZ Advisory", age: 40, neighborhood: "Euroméditerranée", coords: [5.3596, 43.3121],
    zodiac: "Balance",
    linkedin: "linkedin.com/in/rachida-ziani",
    joinedAt: "2023-05-30",
    skills: ["levée de fonds", "modélisation", "due diligence"],
    offers: ["préparation de levée", "recherche d'investisseurs"],
    needs: ["avocate corporate", "pitch deck"],
    hobbies: ["tennis", "échecs", "voyages"],
    bio: "Je prépare les dossiers que les investisseurs lisent jusqu'au bout.",
    knows: ["beatrice"],
  },
  {
    id: "elodie", firstName: "Élodie", lastName: "Garnier", job: "UX designer",
    company: "Freelance", age: 30, neighborhood: "La Friche", coords: [5.3843, 43.3114],
    zodiac: "Poissons",
    linkedin: "linkedin.com/in/elodie-garnier",
    joinedAt: "2024-04-11",
    skills: ["UX research", "prototypage", "design system", "Figma"],
    offers: ["audit UX", "refonte de parcours"],
    needs: ["développeuses partenaires", "mentorat"],
    hobbies: ["skate", "illustration", "café de spécialité"],
    bio: "Je rends les produits évidents à utiliser.",
    knows: [], isNewcomer: true,
  },
  {
    id: "valerie", firstName: "Valérie", lastName: "Nguyen", job: "Recruteuse indépendante",
    company: "Nguyen Talents", age: 46, neighborhood: "Baille", coords: [5.3919, 43.2875],
    zodiac: "Lion",
    linkedin: "linkedin.com/in/valerie-nguyen",
    joinedAt: "2022-03-08",
    skills: ["recrutement cadres", "marque employeur", "sourcing"],
    offers: ["recrutement au succès", "conseil RH"],
    needs: ["clients scale-up", "outils ATS"],
    hobbies: ["cuisine", "marathon", "séries"],
    bio: "Je trouve les personnes que les annonces ne trouvent pas.",
    knows: ["karine", "beatrice"], mentor: true,
  },
  {
    id: "assia", firstName: "Assia", lastName: "Meziane", job: "Fondatrice épicerie fine",
    company: "Le Comptoir d'Assia", age: 37, neighborhood: "Estaque", coords: [5.3270, 43.3601],
    zodiac: "Capricorne",
    linkedin: "linkedin.com/in/assia-meziane",
    joinedAt: "2023-08-21",
    skills: ["retail", "sourcing producteurs", "vente", "animation boutique"],
    offers: ["paniers d'entreprise", "dégustations"],
    needs: ["e-commerce", "réseaux sociaux"],
    hobbies: ["pêche", "cuisine", "marchés"],
    bio: "Les meilleurs producteurs du Sud, sous un même toit.",
    knows: ["nadia"],
  },
  {
    id: "juliette", firstName: "Juliette", lastName: "Bonnet", job: "Naturopathe",
    company: "Cabinet Bonnet", age: 34, neighborhood: "Saint-Barnabé", coords: [5.4231, 43.3005],
    zodiac: "Gémeaux",
    linkedin: "linkedin.com/in/juliette-bonnet",
    joinedAt: "2024-06-18",
    skills: ["nutrition", "accompagnement stress", "ateliers santé"],
    offers: ["ateliers bien-être en entreprise", "consultations"],
    needs: ["entreprises clientes", "visibilité"],
    hobbies: ["yoga", "botanique", "randonnée"],
    bio: "La santé au travail, sans injonction ni gadget.",
    knows: [], isNewcomer: true,
  },
  {
    id: "nour", firstName: "Nour", lastName: "El Amrani", job: "Cheffe de produit",
    company: "Scale-up SaaS", age: 28, neighborhood: "Vieux-Port", coords: [5.3711, 43.2938],
    zodiac: "Scorpion",
    linkedin: "linkedin.com/in/nour-el-amrani",
    joinedAt: "2024-07-02",
    skills: ["product management", "roadmap", "analytics", "growth"],
    offers: ["mentorat produit", "cadrage de MVP"],
    needs: ["mentorat dirigeante", "réseau local"],
    hobbies: ["escalade", "podcasts", "brunch"],
    bio: "Je transforme des intuitions en roadmap défendable.",
    knows: ["elodie"], isNewcomer: true,
  },
  {
    id: "therese", firstName: "Thérèse", lastName: "Kouassi", job: "Consultante formation",
    company: "TK Formation", age: 51, neighborhood: "Castellane", coords: [5.3856, 43.2848],
    zodiac: "Bélier",
    linkedin: "linkedin.com/in/therese-kouassi",
    joinedAt: "2021-09-15",
    skills: ["ingénierie pédagogique", "Qualiopi", "animation", "e-learning"],
    offers: ["création de parcours", "certification Qualiopi"],
    needs: ["plateforme LMS", "designer"],
    hobbies: ["chorale", "lecture", "marche"],
    bio: "Je construis des formations qui passent l'audit et qui servent.",
    knows: ["amelie", "claire", "karine"], mentor: true,
  },
];

export const MEMBERS_BY_ID: Record<string, Member> = Object.fromEntries(
  MEMBERS.map((m) => [m.id, m]),
);

/** Graphe non orienté : on symétrise les relations déclarées. */
export function buildAdjacency(members: Member[] = MEMBERS): Map<string, Set<string>> {
  const adj = new Map<string, Set<string>>();
  for (const m of members) adj.set(m.id, new Set());
  for (const m of members) {
    for (const other of m.knows) {
      if (!adj.has(other)) continue;
      adj.get(m.id)!.add(other);
      adj.get(other)!.add(m.id);
    }
  }
  return adj;
}
